name: Build and Compress Go Application

on:
  push:
    branches:
      - main
    tags:
      - "*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - GOOS: linux
            GOARCH: "amd64"
          - GOOS: linux
            GOARCH: "386"
          - GOOS: windows
            GOARCH: "amd64"
            ext: ".exe"
          - GOOS: windows
            GOARCH: "386"
            ext: ".exe"
          - GOOS: darwin
            GOARCH: "arm64"
          - GOOS: darwin
            GOARCH: "amd64"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx-ucl

      - name: Build the application
        shell: bash
        run: |
          sed -i 's/AppId\s*=\s*".*"/AppId = "${{ secrets.AppId }}"/' main.go
          sed -i 's/AppSecret\s*=\s*".*"/AppSecret = "${{ secrets.AppSecret }}"/' main.go
          GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -ldflags="-s -w" -o bin/main main.go
          rm -f main.go

      - name: Compress with UPX
        run: |
          set +e
          upx --best --lzma -o bin/dandanplay-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.ext }} bin/main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dandanplay-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: bin/dandanplay-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.ext }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: bin/dandanplay-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.ext }}
